name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger the workflow when changes are pushed to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest  # Specify the runner environment

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'  # Or whichever Node.js version you're using

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build React app
      - name: Build React app
        run: npm run build

      # Step 5: Set up SSH key for deployment from the environment secret
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_TOKEN }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      # Step 6: Set up Git remote URL with SSH
      - name: Set up Git remote URL with SSH
        run: git remote set-url origin git@github.com:${{ github.repository }}.git

      # Step 7: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages   # The branch to deploy to
          folder: dist        # Vite output folder
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Optional if you're using SSH
